FROM node:12-alpine as buildContainer
WORKDIR /app
COPY ./package.json ./package-lock.json /app/
RUN yarn install
COPY . /app
RUN yarn build:ssr:prod

# Copy dependency definitions
COPY --from=buildContainer /app/package.json /app

# Get all the code needed to run the app
COPY --from=buildContainer /app/dist/browser /app/dist/browser
COPY --from=buildContainer /app/dist/server /app/dist/server

# Expose the port the app runs in
EXPOSE 4000

# Serve the app
CMD ["yarn", "server"]