version: 2.1
jobs:
  build-and-test:
    docker:
      - image: "circleci/node:12.17.0"
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build:prod
workflows:
    build-and-test:
      jobs:
        - build-and-test
