version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/node:14.16.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # specify any bash command here prefixed with `run: `
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies--{{ checksum "package.json" }}

      - run: yarn format:check

      - run: yarn build:ssr:prod

      - run: tar -czvf dist.tar.gz dist

      - store_artifacts:
          path: dist.tar.gz
